---
title: 'Programming Assignment 2: Lexical Scoping'
author: "Shuaidi Wang"
date: "2023-03-16"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```
1.makeCacheMatrix: This function creates a special "matrix" object that can cache its inverse.
```{r}
makeCacheMatrix <- function( m = matrix() ) {

	## initialize the inverse property
    i <- NULL

  ## to set the matrix
    to_set <- function( matrix ) {
            m <<- matrix
            i <<- NULL
    }

  ## to get the matrix
    to_get <- function() {
  ## Return the matrix
    	m
    }

  ## to set the inverse of the matrix
    set_inverse <- function(inverse) {
        i <<- inverse
    }

  ## to get the inverse of the matrix
    get_inverse <- function() {
  ## Return the inverse property
        i
    }

  ## Return a list of the methods
    list(to_set = to_set, to_get = to_get,
         set_inverse = set_inverse,
        get_inverse = get_inverse)
}
```
2.cacheSolve: This function computes the inverse of the special "matrix" returned by makeCacheMatrix above. If the inverse has already been calculated (and the matrix has not changed), then the cachesolve should retrieve the inverse from the cache.
```{r}
cacheSolve <- function(x, ...) {

    ## return a matrix that is the inverse of 'x'
    m <- x$get_inverse()

    ## return the inverse if its already set
    if( !is.null(m) ) {
            message("getting cached data")
            return(m)
    }

    ## to get the matrix from our object
    data <- x$to_get()

    ## calculate the inverse using matrix multiplication
    m <- solve(data) %*% data

    ## to set the inverse to the object
    x$set_inverse(m)

    ## return the matrix
    m
}
```

